@startuml Wallet

title "Payment by Wallet"

actor Client as client
entity Server as server
database Database as db

client -> server: Request buying products using wallet
server -> db: Check for wallet money
db --> server: Return wallet money

alt "Enough money"
server --> client: Validate payment
else "Not enough Money"
server --> client: You don't have enough money
end

@enduml