@startuml "App"

' autonumber

title "App Sequence Diagram"

actor "SEMO" as user


entity "App View" as app
entity "Login Screen" as login
participant "Server" as request
entity "Rest Controller" as rest

database Database as db


user -> app: Click on marker on map
app -> request: request city data
request -> rest: fetch city data
rest -> db: fetch city data
db --> rest: return city data
rest --> request: get city data
app --> user: view city data

user -> app: Click on menu option
app -> request: request menu view
request -> rest: request menu view
rest -> db: fetch city option data
db --> rest: retreive city data
rest --> request: return images and data view
request --> app: return images and data view
app --> user: view request option data

user -> app: click log out
app -> request: request log out
request --> app: redirect to login
app --> user: redirect to login
user -> login: redirected to login
@enduml